name: CI
on:
  push:
    branches:
      - '**'
  pull_request:

env:
  PATH_TO_APP: sample_flutter
  BUILD_OUTPUT_DIR: ${{ github.workspace }}/build/web

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - run: flutter --version
      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ env.PATH_TO_APP }}
      - name: Run tests
        run: flutter test
        working-directory: ${{ env.PATH_TO_APP }}
      - name: Build web
        run: flutter build web --base-href /${{ github.event.repository.name }}/ -o ${{ env.BUILD_OUTPUT_DIR }}
        working-directory: ${{ env.PATH_TO_APP }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: web-build
          path: ${{ env.BUILD_OUTPUT_DIR }}
