name: Deploy Flutter Web to GitHub Pages
on:
  push:

env:
  PATH_TO_APP : sample_flutter
  BUILD_OUTPUT_DIR: ${{ github.workspace }}/build/web

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          flutter-version: '3.32'
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ env.PATH_TO_APP }}

      - name: Build web
        run: flutter build web --base-href /${{ github.event.repository.name }}/ -o ${{ env.BUILD_OUTPUT_DIR }}
        working-directory: ${{ env.PATH_TO_APP }}

      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_OUTPUT_DIR }}

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4

